######################################################################
##
## Filename: test_crc.udo
## Created on: Thu Nov 05 3:34:10 PM Iran Standard Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
